<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Projects\Sarhne_N-Tier\Sarhne\Sarhne.Domain\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Projects\Sarhne_N-Tier\Sarhne\Sarhne.Domain\.editorconfig" />
  </ItemGroup>


</Project>
