<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="MailKit" Version="4.17.0" />
	  <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.10">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sarhne.Application\Sarhne.Application.csproj" />
    <ProjectReference Include="..\Sarhne.Domain\Sarhne.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EditorConfigFiles Remove="D:\Projects\Sarhne_N-Tier\Sarhne\Sarhne.Infrastructure\.editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <None Include="D:\Projects\Sarhne_N-Tier\Sarhne\Sarhne.Infrastructure\.editorconfig" />
  </ItemGroup>

	<ItemGroup>
		<EmbeddedResource Include="Services\Email\Templates\*.html" />
	</ItemGroup>
	
</Project>
